### PR TITLE
done with the seed file for seeding the products table

### PR DESCRIPTION
**Pull request by curiousYi**
#17 and #15

Done with this.

### CODE REVIEW

**Comment by clocasto** [comment]
Looks good to me - your turn @nrod80

**Comment by clocasto** [comment]
Actually - I think we need to include component products like ram, etc...

**Comment by curiousYi** [comment]
this also includes the seedsorders file #15

**Comment by nrod80** [comment]
I refactored so that the only db contact is in the seed.js file. Also, now seedProducts and seedOrders only export the array of seed data.

**Comment by clocasto** [comment]
Looks good - ready for your stamp @BearGrappler

**Comment by curiousYi** [comment]
Looks good to me #17 and #15

**Pull request merged**
